### ISSUE TITLE
K8 >= v1.6 RBAC

### ISSUE THREAD

**Issue by mknapik1** [PacktPublishing/Getting-Started-with-Kubernetes-Second-Edition#1]
In Chapter 1,  the section titled "Kubernetes UI" instructs us to browse to https://(your master ip)/ui/. However, it offers no guidance on how to set up the required user permissions for our newly created cluster. Anyone with K8s >= v1.6 will not be able to access the Kubernetes UI or dashboard without this step.
See https://github.com/kubernetes/dashboard/issues/1800

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
